---
title: "Continuous Treatment in Propensity Score Analysis"
author: "Megha Joshi"
date: 2019-10-09
categories: ["R"]
tags: ["propensity score analysis", "causal inference", "continuous treatment"]
---

In my qualifying exam, in the written part, I was asked about how to analyze the effect of continuous, not binary, treatment using propensity score analysis. I skipped it for the written but I spent a few days looking up how to analyze this in case I would be asked during my oral examination. Sadly, no one asked me even when I asked them to, so here is a blog detailing my explorations.  

# Binary Treatment

Below let $e(X)$ denote propensity score, $D$ denote a binary treatment, and $X$ denote all the observed confounders. In the case of binary treatment, propensity scores represent the probability of receiving treatment given the covariates:

$$e(X) = P(D = 1|X)$$

We estimate the scores using logistic regression or machine learning techniques like generalized boosted models. 


# Extension to Contiuous Treatment

In binary treatment context, we assume that the potential outcomes are independent of treatment given $X$:

$$Y(1), Y(0) \perp\!\!\!\perp D |X$$

and by extension are independent given the propensity scores:

$$Y(0), Y(1) \perp\!\!\!\perp D|e(X)$$

Hirano and Imbens (2004) introduced the assumption of weak unconfoundedness in context of continuous treatment. They stated: "we do not require joint independence of all potential outcomes. Instead, we require conditional independence to hold for each value of the treatment." Below, the potential outcome given that $T = t$ is unreated to the treatment given the set of covariates:

$$Y(t) \perp\!\!\!\perp T |X$$

To calculate the propensity scores, in the case of continuous treatment, we cannot find the probability that continuous treatment, $T$, equals a given value $t$. The likelihood of continuous variables taking on a given value is zero. For continuous treatment variable, we find the conditional density, the probability that $T$ is infinitely close to $t$. Below let $r(t,x)$ denote the propensity scores. The right hand side of the equation represents the conditional density function of a normal distribution. To estimate the propensity scores, we need to run a linear regression predicting the treatment by a set of covariates. From that we get the fitted values $X\hat{\beta}$ and ${\sigma}^2$ (Austin, 2019). The fitted values take the place of the mean in the density function. 

$$ r(t, x) = {f_{T|X}}^{(t|x)} = \frac{1}{\sqrt{2\pi\hat{\sigma}^2}} e^{-\frac{(t - X\hat{\beta})^2}{2\pi\hat{\sigma}^2}}$$

Conditional on the propensity scores we can assume that each potential outcome is independent of treatment given the propensity scores:

$$Y(t) \perp\!\!\!\perp T |r(t,x)$$

Hirano and Imbens (2004) state that: "Within strata with the same value of $r(t,X)$, the probability that $T = t$ does not depend on the value of $X$.”

$$X \perp\!\!\!\perp 1(T = t)|r(t,x)$$

# Calculating Weights

Following the same logic as the inverse propensity weights (IPW) for the estimation of the average treatment effect (ATE) for a binary treatment, we calculate the inverse of the propensity scores are the weights:

$$\frac{1}{{f_{T|X}}^{(t|x)}}$$

However, Robins et al. (2000) noted that such weights can result in infinite variance (Austin, 2019). They suggested to use stabilized weights as follows:

$$\frac{{f_{T}}^{(t)}}{{f_{T|X}}^{(t|x)}}$$

Here the numerator represents the marginal density of treatment:

$${f_{T}}^{(t)} = \frac{1}{\sqrt{2\pi\hat{\sigma_t}^2}} e^{-\frac{(t - \mu_t)^2}{2\pi\hat{\sigma_t}^2}}$$


# References

Hirano K and Imbens GW. The propensity score with continuous treatments. In: Gelman A and Meng X-L (eds) Applied Bayesian modeling and causal inference from incomplete-data perspectives. Chichester: John Wiley & Sons Ltd, 2004, pp.73–84.

Robins JM, Hernan MA and Brumback B. Marginal structural models and causal inference in epidemiology. Epidemiol 2000; 11: 550–560.






