---
title: "Coronavirus"
author: "Megha Joshi"
date: 2020-03-27
categories: ["R"]
tags: ["coronavirus", "COVID-19", "gganimate", "ggplot", "leaflet"]

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In this post, I am analyzing data on COVID-19 cases worldwide. 

# Libraries

```{r message = FALSE, warning = FALSE}
library(tidyverse)
library(maps)
library(ggthemes)
library(jsonlite)
library(leaflet)
library(widgetframe)
library(lubridate)
library(scales)
```


# Read in the Data

I downloaded the data from [here](https://github.com/CSSEGISandData/COVID-19).

```{r, warning = FALSE, message = FALSE}
confirmed <- read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv") %>%
  pivot_longer(cols = -c(1:4),
               names_to = "date",
               values_to = "confirmed")

deaths <- read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv") %>%
  pivot_longer(cols = -c(1:4),
               names_to = "date",
               values_to = "deaths")

recovered <- read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv") %>% pivot_longer(cols = -c(1:4),
               names_to = "date",
               values_to = "recoveries")


dat <- left_join(confirmed, deaths) %>%
  left_join(recovered) %>%
  mutate(date = mdy(date),
         lab = paste0("Confirmed: ", confirmed)) %>%
  rename(country_region = `Country/Region`)


date <- tibble(date = unique(dat$date)) %>%
  arrange(date) %>%
  mutate(days = row_number())

dat <- dat %>%
  left_join(date, by = "date")
```


# Coronavirus Confirmed Cases

```{r}
covid_leaf <- leaflet(data = dat, options = leafletOptions(minZoom = 1.5)) %>% 
  addProviderTiles(providers$CartoDB.DarkMatter)  %>%
  addCircleMarkers(~Long, ~Lat, radius = ~confirmed/1000, label = ~lab, fillOpacity = .2)

frameWidget(covid_leaf)
```


# Cases by Week

## Confirmed 

```{r, fig.width=8, fig.height=6}
country_dat <- dat %>%
  filter(country_region %in% c("China", "Italy", "Korea, South", "US")) %>%
  mutate(week = cut(date, "week", start.on.monday = FALSE))

country_dat %>%
  ggplot(aes(x = confirmed, y = week)) +
  geom_bar(stat = "identity", position = "dodge", fill = "blue4") + 
  facet_wrap(~ country_region) +
  labs(y = "", x = "Confirmed Cases") + 
  scale_x_continuous(labels = comma) +
  theme_bw()
```

## Deaths

```{r, fig.width=8, fig.height=6}
country_dat %>%
  ggplot(aes(x = deaths, y = week)) +
  geom_bar(stat = "identity", position = "dodge", fill = "red4") + 
  facet_wrap(~ country_region) +
  labs(y = "", x = "Deaths") + 
  scale_x_continuous(labels = comma) +
  theme_bw()
```

## Recoveries

```{r, fig.width=8, fig.height=6}
country_dat %>%
  ggplot(aes(x = recoveries, y = week)) +
  geom_bar(stat = "identity", position = "dodge", fill = "green4") + 
  facet_wrap(~ country_region) +
  labs(y = "", x = "Recovered") + 
  scale_x_continuous(labels = comma) +
  theme_bw()
```

# Confirmed Cases by Days

```{r}
country_dat %>%
  group_by(days, country_region) %>%
  summarize(confirmed = sum(confirmed)) %>%
  ungroup() %>%
  ggplot(aes(x = days, y = confirmed, color = country_region)) +
  geom_line(size = 1) +
  scale_y_continuous(labels = comma) +
  scale_color_brewer(type = "qual", palette = 6) + 
  labs(x = "Days", y = "Confirmed Cases", color = "Country") + 
  theme_bw()
```

