---
title: "Propensity Score Missing Data Examples"
author: "Megha Joshi"
date: 2020-05-16
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Multiple Imputation 

### Multiple Imputation Within

```{r, message = F, warning = F, fig.width = 10}
library(tidyverse)
library(mice)
library(VIM)
library(fastDummies)

hsls_dat <- read_csv("https://raw.githubusercontent.com/meghapsimatrix/datasets/master/causal/HSLS09_incomplete.csv") %>%
  mutate_if(is.character, as.factor) %>%
  mutate_at(vars(repeated_grade, IEP, working_T3), as.factor)


glimpse(hsls_dat)

# aggr(hsls_dat, combined = FALSE, numbers = TRUE)
```


```{r, eval = F}
# running the imputation
system.time(temp_data <- mice(hsls_dat, m = 10, maxit = 10, seed = 20200516))

save(temp_data, file = "temp_data.RData")

# long format data
hsls_all_data <- complete(temp_data, action = "long")

# saving all the temp data
write_csv(hsls_all_data, "hsls_all_data.csv")
```


```{r}
imp_dat_dc <- dummy_cols(hsls_all_data, select_columns =  c("sex", "race", "language", "locale", "region")) %>%
  as_tibble() %>%
  mutate_at(vars(repeated_grade, IEP), as.character) %>%
  mutate_at(vars(repeated_grade, IEP), as.numeric) %>%
  select(-c(sex, race, language, locale, region))

glimpse(imp_dat_dc)

covs <- imp_dat_dc %>%
  select(repeated_grade:math_score_T1, sex_F:region_W)

center_at <- function(x, subset){
   x - mean(x[subset])
}

variables <- names(covs)
```

